apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-invalid-cert
  namespace: example
spec:
  commonName: example.com
  dnsNames:
  - example.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  # Force a validator error by setting a field to a wrong value type
  secretName: 0
