---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: some-app-envoy
  name: some-app-envoy
  namespace: example
spec:
  ports:
  - name: json-rpc-http
    port: 8545
    protocol: TCP
    targetPort: 8545
  selector:
    app: some-app-envoy
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: some-app-envoy
    fluxcd.io/sync-gc-mark: sha256.Tt7X1mr8TndEB2BwarYMCvalr3_uRzvST9Bka6e7KuY
  name: some-valid-deployment
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: some-app-envoy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "9991"
        prometheus.io/scrape: "true"
      labels:
        app: some-app-envoy
    spec:
      containers:
      - image: envoyproxy/envoy:v1.13.1
        imagePullPolicy: IfNotPresent
        name: envoy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-conf
      volumes:
      - configMap:
          defaultMode: 420
          name: envoy-conf
        name: envoy-conf
